before_script:
  - dmenv install --no-develop

stages:
  - check
  - deploy

.check:
  stage: check

check/linux:
  extends: .check
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-check --use-tanker=same-as-branch --profile gcc8-release
  artifacts:
    paths:
      - coverage
    expire_in: 7 days

check/macos:
  extends: .check
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-check --use-tanker=same-as-branch --profile macos-release

check/windows:
  extends: .check
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-check --use-tanker=same-as-branch --profile vs2019-release


.check-deployed:
  stage: check
  when: manual

check/deployed-linux:
  extends: .check-deployed
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-check --use-tanker=deployed --profile gcc8-release

check/deployed-macos:
  extends: .check-deployed
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-check --use-tanker=deployed --profile macos-release

check/deployed-windows:
  extends: .check-deployed
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-check --use-tanker=deployed --profile vs2019-release


.deploy:
  stage: deploy
  when: manual
  only:
    - tags

deploy/linux:
  extends: .deploy
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy --profile gcc8-release

deploy/macos:
  extends: .deploy
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy --profile macos-release

deploy/windows:
  extends: .deploy
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy --profile vs2019-release

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - check/linux
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux
