before_script:
  - dmenv install

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - schedules
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py test

deploy:
  stage: deploy
  when: manual
  tags:
    - LinuxSlave-1
  script:
    - dmenv run -- python run-ci.py deploy
