before_script:
  - dmenv install --no-develop

stages:
  - build
  - deploy

build/linux:
  stage: build
  except:
    - schedules
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py test --runner linux

build/macos:
  stage: build
  except:
    - schedules
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py test --runner macos

deploy/linux:
  stage: deploy
  when: manual
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py deploy --runner linux

deploy/macos:
  stage: deploy
  when: manual
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py deploy --runner macos
