before_script:
  - dmenv install --no-develop

stages:
  - check
  - deploy


select/native-from-sources:
  stage: check
  when: manual
  only:
     - pushes
  script:
      - dmenv install --no-develop
      - dmenv run -- python run-ci.py trigger --native-from-sources

select/deployed-native:
  stage: check
  when: manual
  only:
     - pushes
  script:
      - dmenv install --no-develop
      - dmenv run -- python run-ci.py trigger

.check:
  stage: check
  except:
    - pushes

check/linux:
  extends: .check
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home check --profile gcc8-release

check/macos:
  extends: .check
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home check --profile macos-release

check/windows:
  extends: .check
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home check --profile vs2017-release


.deploy:
  stage: deploy
  when: manual
  only:
    - tags

deploy/linux:
  extends: .deploy
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy --profile gcc8-release

deploy/macos:
  extends: .deploy
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy --profile macos-release

deploy/windows:
  extends: .deploy
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy --profile vs2017-release


mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
