image: 10.100.0.1:5000/ci-cpp:latest


before_script:
  - dmenv install --no-develop
  - export PATH=$(dmenv show:venv_path)/bin:$PATH


stages:
  - check
  - deploy

check/linux:
  stage: check
  except:
    - schedules
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py check --profile gcc8

check/macos:
  stage: check
  except:
    - schedules
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py check --profile macos

deploy/linux:
  stage: deploy
  when: manual
  only:
    - tags
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py deploy --profile gcc8 --git-tag ${CI_COMMIT_TAG}

deploy/macos:
  stage: deploy
  when: manual
  only:
    - tags
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py deploy --profile macos --git-tag ${CI_COMMIT_TAG}


mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
