stages:
  - deploy

deploy/linux:
  stage: deploy
  tags: [linux]
  only:
    - tags
  script:
    - export PATH=$HOME/.local/bin:$PATH
    - python3 -m pip install poetry --user
    - poetry install --no-root
    - poetry run python run-ci.py --isolate-conan-user-home deploy --profile gcc8-release
  artifacts:
    paths:
      - coverage
    expire_in: 7 days
