version: '2.0'

security: # configuration for the `safety check` command
    ignore-cvss-severity-below: 0
    ignore-cvss-unknown-severity: False
    ignore-vulnerabilities:
        73937:
            reason: >
              We need to invest some time to move to Conan 2. Temporarily ignore this vulnerability.
            expires: '2025-09-10'
    continue-on-vulnerability-error: False
