[version]
current = "dev"

regex = '''
  (dev)
  |
  (
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
     post(?P<post>\d+)
     |
     b(?P<beta>\d+)
  )?
  )
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "setup.py"
search = 'version="{current_version}"'

[[file]]
src = "tankersdk/core/tanker.py"
search = '__version__ = "{current_version}"'
